### ISSUE TITLE
请问用docker-compose启动的容器如何进入控制台？

### ISSUE THREAD

**Issue by ClarkeCheng** [LomotHo/minecraft-bedrock#6]
为了方便管理我的容器，我用了docker-compose。但是我在部署bedrock服务器后发现执行`docker attach mcpe`后什么都无法操作，连退出都不行
下面是我的`docker-compose.yml`文件
```
  mcbe:
    image: lomot/minecraft-bedrock
    container_name: mcpe
    network_mode: "host"
    restart: always
    volumes:
      - ../data:/data
```
用`docker run -it`这个方法启动的bedrock容器是可以通过`docker attach mcpe`进入控制台的，但是我不喜欢用这个方式启动容器

**Comment by LomotHo** [comment]
在docker-compose.yml中加上这两行即可
```
stdin_open: true
tty: true
```

下面是刚刚测试通过的完整docker-compose.yml
```
version: '3'

services:
   mcpe: # container name
      build: .
      image: minecraft-bedrock:latest
      ports:
         - 19132:19132/udp
      volumes:
         - /opt/mcpe-data:/data
      restart: always
      stdin_open: true
      tty: true

```
